" =================================================================================================
" Config and Setup
" =================================================================================================

set autoindent                  " always set autoindenting on
set autoread                    " autoupdate file on change
set backspace=indent,eol,start
set clipboard=unnamedplus       " use default windows clipboard
set encoding=utf-8              " default encoding to UTF8
set foldlevel=99                " max folding levels
set foldmethod=indent           " folding of code
set hlsearch
set ignorecase                  " ignore case when searching
set incsearch                   " do incremental searching
set mouse=nvi
set nobackup                    " do not keep a backup file
set noexpandtab
set nowrap
set ruler                       " show the cursor position all the time
set scrolloff=3
set smartindent                 " smart indent
set splitbelow
set splitright
set ttyfast                     " smoother changes
set visualbell

set tabstop=2
set softtabstop=2
set shiftwidth=2


" =================================================================================================
" Cursor shape support : | _ █
" =================================================================================================

let &t_EI = "\<Esc>[2 q"
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50


" =================================================================================================
" Syntax
" =================================================================================================

" Syntax tweaks and additions for C - C++ for my custom types
autocmd FileType c,cpp syntax keyword cCustomType i8 i16 i32 i64 u8 u16 u32 u64 c8
highlight link cCustomType Type


" =================================================================================================
" Plugins
" =================================================================================================

call plug#begin()
  " FZF fuzzy file finding support. 
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'

	" clang plugins for better autocompletion
	Plug 'prabirshrestha/vim-lsp'
	Plug 'prabirshrestha/asyncomplete.vim'
	Plug 'prabirshrestha/asyncomplete-vim-lsp.vim'
	Plug 'mattn/vim-lsp-settings'

	" colors plugins
	Plug 'patstockwell/vim-monokai-tasty' 
call plug#end()

" FZF hotkeys
" Search project files
nnoremap <C-p> :Files<CR>
" Search open buffers
nnoremap <leader>b :Buffers<CR>
" Search text inside files (requires ripgrep)
nnoremap <leader>f :Rg<CR>


" =================================================================================================
" Colors 
" =================================================================================================

syntax on
set termguicolors
set t_ut=                       " fix backgroud color over SSH
set background=dark
colorscheme vim-monokai-tasty
